name: cross-party

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - tqdm
  - jupyter
  - pyspark
  - networkx
  - numpyro
  - python-graphviz
  - pip:
      - statsmodels == 0.13
